[Workspace]
Home=..
AppHTMLPath=AppHtml
AppSrcPath=AppSrc
DataPath=Data
DDSrcPath=DDSrc
BitmapPath=Bitmaps
IdeSrcPath=IdeSrc
HelpPath=Help
ProgramPath=Programs
FileList=Data/Filelist.cfg
Description=DFStack
